### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by santakrooz** [CrossfireCurt/MIOS-IFTTT-Maker#1]
Hi, I've installed the files into my vera lite under apps>develop apps>luup files. However I do not see the device in my device list on the devices page. Hoping to learn how to finish configuring and how to use with IFTTT. 

Many thanks
SK

**Comment by CrossfireCurt** [comment]
Hi @santakrooz, looks like I never actually responded to you :( Did you manage to get this working?
